### ISSUE TITLE
请问默认的省市区是怎么定义的呢

### ISSUE THREAD

**Issue by Recklesslmz** [jcc/v-distpicker#1]
我从接口查询到数据去发现无法同步到组件上去~，请大大解答呀~

**Comment by jcc** [comment]
https://distpicker.iline.co/ 用法上有写明默认的值如何设置。

```javascript
<v-distpicker province="北京市"></v-distpicker>
```

**Comment by Recklesslmz** [comment]
`嗯嗯，是这样的，我从接口获取的默认省市区，我尝过很多种写法，发现都无法同步到组件上去`
`<v-distpicker  :province="memberInfo.province" :city="memberInfo.city" :area="memberInfo.district"
      @province="selectProvince"
      @city="selectCity"
      @area="selectDistrict"></v-distpicker>` 这是组件的代码

data() {
      return {
        pickerValue: '2015-01-01',
        value4: null,
        visible4: false,
        currentValue: '',
        isCanClickFlag: true,
        memberInfo: {},
      }
    }
memberInfo是我通过ajax请求出来的数据，里面会有省市区的字段，我想通过获取数据之后绑定到组件上，但是没有成功。。。。我很疑惑，已经困扰一天了

**Comment by Recklesslmz** [comment]
`      getMemberInfo(){
        this.$http.post(commonUrl + "/restful/member?op=getMember&access_token=111", {
          op: 'getMember',
          partnerId: partnerId,
          openId: openId,
          mobile: '18351816916',
        }).then(response => {
          console.log(response.data)
          this.$data.memberInfo = response.data;
        }, response => {
          // error callback/**/
        });
      },`
这个便是ajax调用 ，其他数据可正常绑定

`<div class="info-main-list">
        <div class="info-list-name">生&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;日</div>
        <div class="infi-list-text">
          <input class="list-date" type="date" v-model="memberInfo.birthday"
                 placeholder="生日">
        </div>
      </div>
      <v-distpicker  :province="memberInfo.province" :city="memberInfo.city" :area="memberInfo.district"
      @province="selectProvince"
      @city="selectCity"
      @area="selectDistrict"></v-distpicker>`

代码中，生日可正常显示，但组件数据无法同步，我确认memberInfo中的省市区不为空的

**Comment by jcc** [comment]
为何要 `this.$data.memberInfo` 这样赋值，而不是 `this.memberInfo` ? 而且你的 markdown 格式请排整齐，看得很辛苦。

**Comment by Recklesslmz** [comment]
不好意思，我第一次使用这个功能还不是很懂~。。。`this.memberInfo`这样的赋值也是不可以的，我尝试只有在data()里这样写才是可以的`memberInfo:{province:'江苏省'，city:'南京市'}`

**Comment by jcc** [comment]
你这里打开页面的时候已经载入了 `v-distpicker` 组件，此时，你的 `memberInfo` 对象还是空的，直接传递给组件的属性，所以当你 `ajax` 加载完，有数据，但现实还是为空。

解决方法之一：设置一个布尔值的变量 `show`，通过计算属性判断 `memberInfo.province` 是否存在，存在则 `show` 为 `true` 否则为 `false`

**Comment by Recklesslmz** [comment]
感谢大大，已经解决啦~
