### ISSUE TITLE
选完地区后重新选择市会触发selected事件

### ISSUE THREAD

**Issue by Fa-haxiki** [jcc/v-distpicker#106]
先选完一遍省市区，然后关闭弹窗，再打开重新选择市，就会触发selected事件，这不是大家想要的吧
getCities() {
      this.currentCity = this.placeholders.city
      this.currentArea = this.placeholders.area
      this.cities = this.determineValue(this.currentProvince, this.placeholders.province)
      this.cleanList('areas')
      if (this.cities.length === 0) {
        this.emit('selected')
        this.tab = 1
        this.showCityTab = false
      }
    },

**Comment by wwhwwhwwh** [comment]
v1.3.1 已修复。增加change 事件，select 已重构
