### ISSUE TITLE
VDistpicker 最新版本1.2.2中遇到的问题

### ISSUE THREAD

**Issue by dachengzi86** [jcc/v-distpicker#107]
选择**重庆市-市辖区-江北区**报错，Error in callback for watcher "currentArea" : TypeError : Cannot read property 'slice' of undefined

**Comment by mynameisforever** [comment]
有解决办法么，同遇到相同问题

**Comment by hclscut** [comment]
这个问题看源代码已经解决过了，不过应该没有发布编译后的代码/dist/v-distpicker，辛苦作者有空发布下吧

**Comment by dq77** [comment]
很奇怪 源码看起来已经解决了，但是依然报错，而且其他的由于重复区名导致的问题已经都修复了 比如朝阳区 铁西区 都是重复区名 都没问题 唯独这个重庆市江北区
