### ISSUE TITLE
大神，address-header，address-container添加不上样式怎么解决，moblie下

### ISSUE THREAD

**Issue by sunyonghua** [jcc/v-distpicker#11]
大神，address-header，address-container添加不上样式怎么解决，moblie下

**Comment by jcc** [comment]
@sunyonghua 你是怎么调用的？

**Comment by sunyonghua** [comment]
npm 然后使用时只有把scoped去掉才可以，

**Comment by jcc** [comment]
@sunyonghua 嗯，你需要用全局样式，scoped 的话只是局部样式，只用在当前组件上。
