### ISSUE TITLE
直辖市下级文字太长了

### ISSUE THREAD

**Issue by adophper** [jcc/v-distpicker#12]
还请作者别建议我的修改。

例：北京市下面是北京市市辖区，最后串联直来就是北京市北京市市辖区，可以考虑将北京市市辖区缩短成市辖区。

我项目中适当修改了一下这个地方。
html里在三个selecte 的option下面添加了自定义属性：
:data-code="index"

script里面的修改:
data里面增加了：
currentProvinceCode: '',
        currentCityCode: '',
        currentAreaCode: ''

然后在：
getAreas()方法里将：
his.areas = this.determineValue(this.currentCity, this.placeholders.city)
修改成了：
this.currentCityCode = this.$refs.city.options[this.$refs.city.selectedIndex].getAttribute('data-code');
if(this.currentCity == this.placeholders.city) {
          this.areas = []
        } else {
          this.areas = this.getDistricts(this.currentCityCode)
        }

**Comment by jcc** [comment]
@adophper 可以提 pr 给我吗？

**Comment by jcc** [comment]
@adophper 重新看了一下你写的那一段，没必要吧？我那个属性本支持字符串或者 code 的传递，二选一即可。
