### ISSUE TITLE
数据错误，北京市下面的区域也是

### ISSUE THREAD

**Issue by anrui0219** [jcc/v-distpicker#120]
ps:用的是vue3.0，不知道是否与这个有关

问题一：数据错误
![image](https://user-images.githubusercontent.com/44487076/84130317-b69f2500-aa75-11ea-946b-347e38d544a9.png)

问题二：选择后再点击市，也会触发selected和selectArea的方法

**Comment by jcc** [comment]
@anrui0219  1.2.6 版本试一下

**Comment by jcc** [comment]
#121
