### ISSUE TITLE
1.2.5版本对于北京等直辖市的选择依然不能选择到区

### ISSUE THREAD

**Issue by Jyx-0809** [jcc/v-distpicker#121]
![image](https://user-images.githubusercontent.com/59909582/84131586-514c3380-aa77-11ea-8694-3b1465415015.png)

**Comment by jcc** [comment]
Ok, 我知道了，忘记编译，稍等哈

**Comment by jcc** [comment]
@Jyx-0809 1.2.6 版本试一下

**Comment by Jyx-0809** [comment]
已解决，谢谢
