### ISSUE TITLE
插件初始化参数，直辖市设置三级值有问题(v1.26)

### ISSUE THREAD

**Issue by Ushio568** [jcc/v-distpicker#123]
![image](https://user-images.githubusercontent.com/67620351/86081968-4a8a6c80-bac9-11ea-9df0-d93976a1edab.png)
而且还会造成后续选择问题

**Comment by QrnKG** [comment]
我这里的解决方法是先置空，定时1秒后再显示。就没问题了。怀疑可能是初始化时的问题

**Comment by Ushio568** [comment]
> 我这里的解决方法是先置空，定时1秒后再显示。就没问题了。怀疑可能是初始化时的问题

作者合并了分支，我试了下  如果是使用多个，直辖市设置第二个就会开始不显示 我把源码拉出来测试了下， 发现触发了city的watch就会正常回显
