### ISSUE TITLE
兼容性问题 在微信PC端的网页不适用 

### ISSUE THREAD

**Issue by ninger980213** [jcc/v-distpicker#129]
就是在微信打开的提交省市区提交不上去
![啊啊啊](https://user-images.githubusercontent.com/63433029/89878064-a3cedb00-dbf3-11ea-8d95-386cbe415f4b.jpg)

**Comment by jcc** [comment]
提交不上去是指？事件没有返回值吗？

**Comment by ninger980213** [comment]
对就是这个意思  获取不到我选择的省市区

**Comment by jcc** [comment]
你是怎么调用的，可否提供一些那一段代码？

**Comment by ninger980213** [comment]
在页面这样写的
![1](https://user-images.githubusercontent.com/63433029/90086035-105ced80-dd4c-11ea-8898-cb0eb53c1f98.jpg)
在方法中
![2](https://user-images.githubusercontent.com/63433029/90086087-2d91bc00-dd4c-11ea-95c4-1d5650ae8055.jpg)
调用的时候
![3](https://user-images.githubusercontent.com/63433029/90086101-34b8ca00-dd4c-11ea-8cbc-7565cef314fb.jpg)

**Comment by ninger980213** [comment]
![1](https://user-images.githubusercontent.com/63433029/90086149-531ec580-dd4c-11ea-8cf1-a0b3502f4fac.jpg)
![2](https://user-images.githubusercontent.com/63433029/90086157-574ae300-dd4c-11ea-95c8-9d4bc9c7a8a2.jpg)
![3](https://user-images.githubusercontent.com/63433029/90086163-5a45d380-dd4c-11ea-8f71-19f858becbcb.jpg)
