### ISSUE TITLE
如果使用vue dist发布版引入component没有进行渲染

### ISSUE THREAD

**Issue by zhaojunlike** [jcc/v-distpicker#13]
在我的老项目中，并不是前端工程。如果我使用seajs 导入进来，页面没有报错，但是并没有进行渲染。
![image](https://user-images.githubusercontent.com/13638996/28774575-a489e90e-7620-11e7-92dd-0a86d56e368f.png)

并且直接使用<script></script>引入也不行。

**Comment by jcc** [comment]
@zhaojunlike 没有任何报错吗？

**Comment by zhaojunlike** [comment]
可以的，vuejs正常，包括我使用的vuePager也是正常的，页面不报错，发现是没有正常进行渲染
![image](https://user-images.githubusercontent.com/13638996/28805149-878b0f66-769a-11e7-8e51-2d0854158485.png)

**Comment by zhaojunlike** [comment]
我非常希望，能在项目中使用到它，也需要使用到它，如果您有空，希望您能帮忙看看

**Comment by jcc** [comment]
你命名组件跟调用标签错了吧？你试一下 <area-picker></area-picker>

**Comment by zhaojunlike** [comment]
是对的哈，这个我都是试过，100%确认过

**Comment by jcc** [comment]
@zhaojunlike 你能加一下我 Q 么？601360343，我暂时也不知道问题所在。

**Comment by jcc** [comment]
使用 `VDistpicker.default` 即可解决.

```
<script src="http://cdn.bootcss.com/vue/2.4.2/vue.min.js"></script>
<script src="./node_modules/v-distpicker/dist/v-distpicker.js"></script>
<script type="text/javascript">
    Vue.component('v-distpicker', VDistpicker.default)
    new Vue({
        el: '#app'
    })
</script>
```

**Comment by zhaojunlike** [comment]
thanks
