### ISSUE TITLE
省直辖县code问题存在错误

### ISSUE THREAD

**Issue by lyxxxh** [jcc/v-distpicker#138]
### 问题截屏
![image](https://user-images.githubusercontent.com/35553218/100048996-39177780-2e51-11eb-83b5-3537e3b1f084.png)

![image](https://user-images.githubusercontent.com/35553218/100048964-24d37a80-2e51-11eb-9630-015da9395cc0.png)

![https://cdn.lblog.club/git/qwersqwe.png](https://cdn.lblog.club/git/qwersqwe.png)

省 `code` 和 城市 `code` 一样? 这明显是错误。

直辖市都会出现这个问题。

### 解决1 (直接改扩展包源码):
`import Distpicker from 'v-distpicker'`  
实际是`import node_modules/_v-distpicker@1.2.8@v-distpicker/dist/v-distpicker.js`
这代码是编译压缩后,网上找个格式化js,在 `emit` 方法加上。
`this.currentProvince`

![image](https://user-images.githubusercontent.com/35553218/100050010-8ac10180-2e53-11eb-807d-3859e84a4898.png)
![image](https://user-images.githubusercontent.com/35553218/100050127-c1971780-2e53-11eb-9e18-8e1d51d8110e.png)

### 解决2 (规范些)
复制node_modules/v-distpicker/src` 的代码,
自己封装成一个组件, 同上。

### 扯淡
读了几小时源码 代码又不多 愣是没读懂。
注释没有 风格看着难受。
这应该是4年轻的代码,我想作者都升级版本了, 也可以优化下代码。

![image](https://user-images.githubusercontent.com/35553218/100050821-40408480-2e55-11eb-9470-65f17ca78eb9.png)

我只是想轻轻松松用功能 不希望客户 `艾特` 我问题出现。
哎 无奈。

**Comment by jcc** [comment]
非常抱歉，给你带来不好的体验，由于工作原因，此项目更新比较少。此问题已修复，版本号 1.2.9

我会写bug <notifications@github.com> 于2020年11月24日周二 下午2:42写道：
