### ISSUE TITLE
IE11 报错 对象不支持“values”属性或方法 callback for watcher ""  然后没有获取到返回值

### ISSUE THREAD

**Issue by liushuai05** [jcc/v-distpicker#142]
最开始客户反馈有这个问题还不太相信，反复测试后锁定问题，当area发生变化的时候就出现这个错误！

**Comment by liushuai05** [comment]
估计是触发onSelected方法的时候引发的这个报错，最初我们这边使用的是onSelected方法取值结果一直取不到，后面就使用了 @province="onChangeProvince"    @city="onChangeCity"  @area="onChangeArea"  结果发行触发 @area="onChangeArea" 时就报错了， @area="onChangeArea" 方法内部也没有执行

**Comment by liushuai05** [comment]
看了一下源码是，Object.values 这个东西IE不支持，正在寻找替代方案，不知道有木有朋友遇到

**Comment by liushuai05** [comment]
解决方案如下（临时修复代码写得比较烂）这是一个地方的解决方法，一共好像要解决2-3个地方，我这边先临时用起来希望大佬能更新上去，如果大佬比较忙我帮忙更新大佬通过一下也可以：

 getCodeByArea(value) {
      let code
	  
	  // Object.values(this.areas).forEach((item, key) => {
       // if (item === value) {
       //   code = Object.keys(this.areas)[key]
       // }
      //})
	  
	  //解决IE不兼容 Object.values问题
	  
	  //获取所有key
	var arr_keys = Object.keys(this.areas);
	for (var i=0; i<arr_keys.length; i++) {
	   if (arr_keys[i] === value) {
          code = Object.keys(this.areas)[i]
        }
	}
      return code
    },

**Comment by 15572389021** [comment]
这地方是不是写错了，传入的参数value是字符串，，在循环里比较的时候用的是this.areas的key。
我改下代码提交pull Request了， 你可以看下，如果有问题咱们可以讨论下
