### ISSUE TITLE
区级同名的情况可能会引发错误

### ISSUE THREAD

**Issue by aiselo** [jcc/v-distpicker#16]
看了源码，是通过中文名找到对应的数字代号，问题是区级同名的情况比较多，会出错：
北京市->市辖区->朝阳区
吉林省->长春市->朝阳区

**Comment by jcc** [comment]
@aiselo ok，也可以提 pr 给我

**Comment by jcc** [comment]
@aiselo 你在测试一下。哈，已修复。

**Comment by Anliny** [comment]
江北区（有两个）  也会出现错误

**Comment by dq77** [comment]
江北区也有此问题
