### ISSUE TITLE
重庆下属县没有数据

### ISSUE THREAD

**Issue by kongoldwant** [jcc/v-distpicker#176]
重庆如下县城没有数据，自己修改了aera.js 。请教下该如何编译呢

500229:'城口县',
500230:'丰都县',
500231:'垫江县',
500233:'忠县',
500235:'云阳县',
500236:'奉节县',
500237:'巫山县',
500238:'巫溪县',
500240:'石柱土家族自治县',
500241:'秀山土家族苗族自治县',
500242:'酉阳土家族苗族自治县',
500243:'彭水苗族土家族自治县',

**Comment by wwhwwhwwh** [comment]
已修复
