### ISSUE TITLE
如何与async-validator组合使用

### ISSUE THREAD

**Issue by CracKerMe** [jcc/v-distpicker#178]
如题，我需要配合 async-validator 使用， 当前 无法配置使用trigger
诉求。地区选择完成后，关闭 【请选择地区】的提示
codesanbox demo：[https://codesandbox.io/s/v-distpicker-biao-dan-yan-zheng-kj8ls7?file=/src/App.vue](https://codesandbox.io/s/v-distpicker-biao-dan-yan-zheng-kj8ls7?file=/src/App.vue)

**Comment by wwhwwhwwh** [comment]
```vue
<v-distpicker
        :province="formData.province"
        :city="formData.city"
        :area="formData.area"
        @selected="selectArea"
      ></v-distpicker>
```
```javascript
const rules = ref({
      area: [
        {
          type: "any",
          required: true,
          message: "请选择地区",
          validator(_rule, value) {
            if (value === "区"||value==="") {
              return new Error("请选择地区");
            }
            return true;
          },
          trigger: ["blur", "change", "click"],
        },
      ],
    });
const selectArea = ({ province, city, area }) => {
      // ...
      handleValidateButtonClick()
    };
const handleValidateButtonClick = (e) => {
      e&&e.preventDefault()
       // ...
}
```

**Comment by CracKerMe** [comment]
> ```
> <v-distpicker
>         :province="formData.province"
>         :city="formData.city"
>         :area="formData.area"
>         @selected="selectArea"
>       ></v-distpicker>
> ```
> 
> ```js
> const rules = ref({
>       area: [
>         {
>           type: "any",
>           required: true,
>           message: "请选择地区",
>           validator(_rule, value) {
>             if (value === "区"||value==="") {
>               return new Error("请选择地区");
>             }
>             return true;
>           },
>           trigger: ["blur", "change", "click"],
>         },
>       ],
>     });
> const selectArea = ({ province, city, area }) => {
>       // ...
>       handleValidateButtonClick()
>     };
> const handleValidateButtonClick = (e) => {
>       e&&e.preventDefault()
>        // ...
> }
> ```

可以理解为：自己通过事件再去走一下`handleValidateButtonClick `的方法， 但是 `trigger `本身的配置依旧是无效的 是么

**Comment by wwhwwhwwh** [comment]
本身配置的自定义事件和原生事件类型不同，暂时不支持，后续版本再考虑

**Comment by CracKerMe** [comment]
感谢回答
