### ISSUE TITLE
能否自定义样式，能否给出例子如何修改样式

### ISSUE THREAD

**Issue by Rido-codes** [jcc/v-distpicker#182]
参考了网上的一些内容但是仍然无法修改

**Comment by wwhwwhwwh** [comment]
Vue3
```vue
<div class="my-form">
    <v-distpicker province="广东省" city="广州市" area="海珠区"></v-distpicker>
  </div>
<div class="my-form">
    <v-distpicker province="广东省" wrapper="my-distpicker" city="广州市" area="海珠区"></v-distpicker>
  </div>

<style >
//方式1：全局css (确保 select 的优先级大于默认的 .distpicker-address-wrapper select)
.my-form .distpicker-address-wrapper select{
  color: red;
  width: 200px;
} 
</style>
//方式2：scoped
<style scoped>
:deep(.distpicker-address-wrapper) select{
  color: red;
  width: 200px;
} 
</style>
//方式3：使用wapper [不使用 scoped,同时删除:deep 也生效]
<style scoped>
:deep(.my-distpicker) select{
  color: #409eff;
  width: 130px;
  height: 32px;
  line-height: 32px;
  margin: 0 3px;
}
:deep(.my-distpicker) select option{
    padding: 5px 12px;
    overflow: hidden;
    color: rgba(0,0,0,.65);
    font-weight: 400;
    font-size: 14px;
    line-height: 22px;
    color: red;
}
</style>

```
Vu2（>2.6）
```vue
<style scoped>
::v-deep .distpicker-address-wrapper select{
  color: red;
  width: 200px;
}
::v-deep .distpicker-address-wrapper select{
  color: green;
  width: 200px;
}
</style>
```

**Comment by Rido-codes** [comment]
非常感谢




　&nbsp;
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jcc/v-distpicker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月4日(星期六) 上午10:27
***@***.***&gt;;
抄送:&nbsp;"　 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [jcc/v-distpicker] 能否自定义样式，能否给出例子如何修改样式 (Issue #182)





 
Vue3
 <div class="my-form"&gt;     <v-distpicker province="广东省" city="广州市" area="海珠区"&gt;</v-distpicker&gt;   </div&gt; <div class="my-form"&gt;     <v-distpicker province="广东省" wrapper="my-distpicker" city="广州市" area="海珠区"&gt;</v-distpicker&gt;   </div&gt; <style &gt; //方式1：全局css (确保 select 的优先级大于默认的 .distpicker-address-wrapper select) .my-form .distpicker-address-wrapper select{   color: red;   width: 200px; }  </style&gt; //方式2：scoped <style scoped&gt; :deep(.distpicker-address-wrapper) select{   color: red;   width: 200px; }  </style&gt; //方式3：使用wapper [不使用 scoped,同时删除:deep 也生效] <style scoped&gt; :deep(.my-distpicker) select{   color: #409eff;   width: 130px;   height: 32px;   line-height: 32px;   margin: 0 3px; } :deep(.my-distpicker) select option{     padding: 5px 12px;     overflow: hidden;     color: rgba(0,0,0,.65);     font-weight: 400;     font-size: 14px;     line-height: 22px;     color: red; } </style&gt; 
 
Vu2（&gt;2.6）
 <style scoped&gt; ::v-deep .distpicker-address-wrapper select{   color: red;   width: 200px; } ::v-deep .distpicker-address-wrapper select{   color: green;   width: 200px; } </style&gt;
