### ISSUE TITLE
默认设置直辖市时地区渲染数据都是北京市数据，此时应该先判断省份

### ISSUE THREAD

**Issue by anchenlee** [jcc/v-distpicker#21]

**Comment by jcc** [comment]
@anchenlee 你设置默认直辖市时，有设置默认的城市吗？

**Comment by anchenlee** [comment]
有的，
![image](https://user-images.githubusercontent.com/7531539/32039283-0e1fedc2-ba60-11e7-8028-c306b80814d4.png)
这是默认设置和对应错误回显，找了一下如果是直辖市的情况 要传 check参数，你试下
`this.areas = this.getDistricts(this.getAreaCode(this.determineType(this.city), this.area))`
![image](https://user-images.githubusercontent.com/7531539/32039359-56fd41c0-ba60-11e7-9219-4a726bd02013.png)

**Comment by jcc** [comment]
嗯嗯，我之前该非移动端的时候忘记改移动端的了。更新一下。感谢~
