### ISSUE TITLE
v-distpicker 如何禁用

### ISSUE THREAD

**Issue by hfq-chenkeke** [jcc/v-distpicker#22]
如何禁用呀

**Comment by jcc** [comment]
如何禁用？哈，暂时没有禁用的，你可以提交个 pr 给我？

**Comment by hfq-chenkeke** [comment]
我现在有个功能，要有权限才能选择，有没有别的办法

**Comment by jcc** [comment]
你可以有权限才显示对应组件

**Comment by hfq-chenkeke** [comment]
操蛋的需求默认都禁止选择，隐藏了，我想他不会同意的

**Comment by jcc** [comment]
或者你可以给一个假的，有权限就显示真的

**Comment by hfq-chenkeke** [comment]
你这还真是个办法，谢谢，你别忘了加上禁用的选项

**Comment by hfq-chenkeke** [comment]
![image](https://user-images.githubusercontent.com/27851284/32040110-379ca390-b9f5-11e7-9dea-3d6c7380aea7.png)  是不是重名了

**Comment by jcc** [comment]
地区的是 area

**Comment by jcc** [comment]
@hfq-chenkeke 你的禁用是使用 PC 模式的时候的么？

**Comment by hfq-chenkeke** [comment]
是的PC端 ，用vue写的，所以想用你的插件，写的很好，能不能现在加一个参数，让他禁用呀，跪求
![image](https://user-images.githubusercontent.com/27851284/32040242-bbab636a-b9f5-11e7-8188-12ae32750895.png)

**Comment by hfq-chenkeke** [comment]
您给加吗？大神  （-_-"）

**Comment by jcc** [comment]
已加上 `disabled` 属性

**Comment by hfq-chenkeke** [comment]
这么快

**Comment by hfq-chenkeke** [comment]
你是不是没有更新文档，我这样加不好使
![image](https://user-images.githubusercontent.com/27851284/32041228-f8ff97ec-b9f8-11e7-9640-59550f8b06b3.png)

**Comment by jcc** [comment]
直接标签里面加 `disabled` 或者 `:disabled="true"` ，文档有缓存吧
