### ISSUE TITLE
选择澳门或香港时依旧显示“区”的下拉选项。

### ISSUE THREAD

**Issue by paloWeiZhu** [jcc/v-distpicker#24]
建议最好可以通过v-mode返回说选的省市区
建议最好可以动态设置省、市、区的数据
当选择香港或澳门时省、市后就结束了，但现在还是会一直显示空的“区”下拉选

**Comment by jcc** [comment]
OK，我看看怎么改比较好

**Comment by jcc** [comment]
@paloWeiZhu v-model 的方式想过，但是不适合于此组件，动态设置省市区数据，这个有待考虑，还没有比较好的方案来处理。

**Comment by paloWeiZhu** [comment]
v-model可以的，默认直接传整个地址对象不就好了，最好支持配置，自己可以定制结果对象。

具体地址的值也可以考虑用数字表示嘛，提供一个数字转具体对象的翻译就好了。

我现在就是在你组件外包一层来支持v-model每当最后选择的事件触发更新v-model的值。

**Comment by Xiao-bin** [comment]
选择香港或澳门的地区时会报Cannot read property 'length' of null的，还有台湾的城市加载不出来，最后能不能完善一下初始化可以是任意值，不用进行检验，因为有些需求并不是必须要区，希望为空的值也能作为初始化

**Comment by jcc** [comment]
@Xiao-bin 我看看，我之前 `updated` 了一下，你更新看看还有没有。不要区的话可以传个参数过滤掉的。

**Comment by Xiao-bin** [comment]
不是不要区，是说根据数据库传过来的地址初始化，但是数据库的地区这个值可能是空的，那进行初始化 :area="area"就会报错，希望能改一下这个，还有你的开发文档最后说明Method的获取选择地区的方法写错了单词，你可以改一下

**Comment by Xiao-bin** [comment]
我下的版本是1.0.12版的，刚才的问题还是存在

**Comment by jcc** [comment]
好，我迟点看看，我想去修电脑。

发自我的 iPhone

**Comment by Xiao-bin** [comment]
不用太急的，已经很感谢你的分享了

**Comment by Xiao-bin** [comment]
那个地区传空值过去是可以了，我之前以为传个‘区’过去，原来是传空字符串，还有你开发文档那个重置Reset Button没有代码展示，希望能补充下

**Comment by Xiao-bin** [comment]
使用的时候跟说明文档不一样，一开始并没有显示区，要等选了市之后才显示，希望能解决一下

**Comment by jcc** [comment]
@Xiao-bin 一开始并没有显示区是我最近优化的，就是选了市才会显示区
