### ISSUE TITLE
如何清空那？

### ISSUE THREAD

**Issue by hfq-chenkeke** [jcc/v-distpicker#28]
我切换单选按钮的时候如何选择的城市清空那？

**Comment by jcc** [comment]
什么意思？

**Comment by hfq-chenkeke** [comment]
就是我选择完省市之后，然后又想通过切换单选按钮，清空选择的省市，可是发现无法联动，清空不了，因为你的组件上不能绑定v-model , 现在是想知道，如何通过切换按钮清空那
![image](https://user-images.githubusercontent.com/27851284/32773284-4c19fdf6-c8ee-11e7-95cf-eb613dc968a3.png)

**Comment by hfq-chenkeke** [comment]
<v-distpicker  @selected="onSelected" v-model="province"></v-distpicker>
这是我理想中的。
这个组件现在不支持联动，也没有默认清空，可以增加一个属性，然后可以重置这个组件吗？或者可以绑定v-model也可以

**Comment by jcc** [comment]
@hfq-chenkeke 文档有重置例子，请移步文档查看

**Comment by hfq-chenkeke** [comment]
![image](https://user-images.githubusercontent.com/27851284/32773938-62d8bad0-c8f0-11e7-88cb-fb9a11a31beb.png)
那个是重置，我找了半天

**Comment by jcc** [comment]
[ResetButton](https://github.com/jcc/v-distpicker/blob/master/examples/components/BaseUsage/ResetButton.vue) 看看这里，文档我忘记弄那个 Reset Button 代码示例了
