### ISSUE TITLE
Failed to mount component: template or render function not defined

### ISSUE THREAD

**Issue by insub** [jcc/v-distpicker#29]
Vue版本： v2.4.4
VDistpicker使用的是umd的最新版本
`Vue.component('v-distpicker', VDistpicker)`
使用
`<v-distpicker></v-distpicker>`

console 报错：
```
vue.js:482 [Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <VDistpicker>
       <Root>
```

**Comment by jcc** [comment]
@insub 请你先检查一下有没有引入。报错信息已很明确

**Comment by insub** [comment]
@jcc 我奇怪的就是这个，我引入了
我是在非单页面上使用的

在页面上我首先引入了 v-distpicker.js，或者说，我认为这样就已经是引入库了，因为从console打印VDistpicker是有对象的。
`<script src="/libs/v-distpicker.js"></script>`

然后注册了一个全局组件
`
<script>
    Vue.component('v-distpicker', VDistpicker)
</script>
`
然后在页面中引入组件：
<v-distpicker></v-distpicker>
然后就报错了: template or render function not defined.

从文档来看，我似乎是已经正确引入了？而且这个页面上同样引入方式也还加载了其它诸如无限刷新，上传等组件库，使用都正常。

抱歉，我是个新手哈，请问我这样引入，是不是那里有问题？

**Comment by insub** [comment]
已解决
[＃30](https://github.com/jcc/v-distpicker/issues/30)
