### ISSUE TITLE
严重bug，当还原为默认选项-省-

### ISSUE THREAD

**Issue by heby** [jcc/v-distpicker#3]
当把省还原为-省-默认选项时，市的值会变成省的值，区的值也没有清空。

**Comment by jcc** [comment]
你好，你是指 `mobile` 的还是 `select` 框的？

**Comment by heby** [comment]
select框的值没有复原。

**Comment by jcc** [comment]
@heby 请问你还原的代码是怎么写的？能否将情况讲详细点？

**Comment by heby** [comment]
@jcc 我还没写代码，就用的官方示例，而且官网上的demo就有这个问题。网络不行，上传不了图片。

**Comment by jcc** [comment]
哦。我大概知道你所说的情况了，官方示例里面，有些例子是共用一个数据绑定数据，所以请你可以尝试刷新页面后再试一下你那个例子。

**Comment by heby** [comment]
这个跟例子没有关系吧，我刚建了个项目测试了一下，而且没有写任何其他代码，只是照抄官方的注册代码，同样的问题，选择某个省后，然后我又复原到默认选项-省-，市的select的选项会直接变成省的选项，正常的逻辑应该是复原到-市-，选项为空，我看了https://github.com/fengyuanchen/distpicker的例子，并没有这个问题，我现在正在看源码。

**Comment by jcc** [comment]
官方示例所有 select 都会有这种情况吗？我还是不怎么懂你所说的情况。市的select的选项会直接变成省的选项？

**Comment by heby** [comment]
我发个邮件给你吧，传个gif图你就明白了

**Comment by jcc** [comment]
@heby fixed，感谢
