### ISSUE TITLE
AMD方式引入时需要用VDistpicker.default来注册组件

### ISSUE THREAD

**Issue by insub** [jcc/v-distpicker#30]
如果在页面上用<script src="">引入v-distpicker.js，在注册为VUE全局组件时会报错，之前提过一个issue：
[＃29](https://github.com/jcc/v-distpicker/issues/29)
`Failed to mount component: template or render function not defined`

而如果将注册为全局组件的代码从：
`Vue.component('v-distpicker', VDistpicker)`
改为：
`Vue.component('v-distpicker', VDistpicker.default)`
那么就不会报错了

我不太清楚这个算不算BUG， @jcc

**Comment by jcc** [comment]
emmm...对了。我 `export default` 了。所以你调用的时候需要这样用 `VDistpicker.default`

**Comment by insub** [comment]
@jcc 明白了，谢谢

**Comment by jcc** [comment]
哈，我在输出的，`index.js` 中写成这样子了 `export default VDistpicker`，去掉 `default` 还有待测试一下才行。
