### ISSUE TITLE
数据没有双向绑定

### ISSUE THREAD

**Issue by insub** [jcc/v-distpicker#31]
Vue版本是2.4.4
是用的在页面上直接引入v-distpicker.js的方式引入组件，发现当选择的地区改变时，数据没有同步到$data上去....

![image](https://user-images.githubusercontent.com/24202/33237758-62889b88-d2b7-11e7-906a-3d299bdcc600.png)

Vue实例的$data如下：

![image](https://user-images.githubusercontent.com/24202/33237782-2e7528a6-d2b8-11e7-846a-69ee8a890bdb.png)

**Comment by jcc** [comment]
@insub 请你提供你的代码实现.
