### ISSUE TITLE
关于数据的双向绑定

### ISSUE THREAD

**Issue by insub** [jcc/v-distpicker#32]
Vue版本是2.4.4
是用的在页面上直接引入v-distpicker.js的方式引入组件，发现当选择的地区改变时，数据没有同步到$data上去....

代码实现：
[https://jsfiddle.net/fjjuqo61/](https://jsfiddle.net/fjjuqo61/)

**Comment by jcc** [comment]
@insub 请你先认真查阅 [文档](https://distpicker.iline.co/) 后再使用。

https://jsfiddle.net/cjjian/fjjuqo61/1/

**Comment by insub** [comment]
@jcc 好的，谢谢，文档看到了的，现在也是这样处理的。主要是没想到必须事件触发，不是双向绑定.....
