### ISSUE TITLE
初始时 地区无法显示

### ISSUE THREAD

**Issue by chengming9731** [jcc/v-distpicker#35]
v-distpicker@1.0.13版本, 在页面初始加载时, 地区无法显示在页面中(根本没加载进来), 但是选择了 市 之后才会出现

**Comment by dafeng17** [comment]
现在初始是好像也显示不了区，只有省市？

**Comment by jcc** [comment]
@dafeng17 之前优化后做了处理，由于有些市没有区，所有一开始先隐藏了。
