### ISSUE TITLE
组件默认值是否支持地区编码？ 

### ISSUE THREAD

**Issue by raisezhang** [jcc/v-distpicker#38]
存储一般仅仅存储地区编码，映射地区名称有点麻烦

要实现两种：
1、要么组件提供映射工具方法，然后反查出地区名称
2、参数支持地区编码，当然这个对使用者而言最简单

多谢啦~    看你那边之前有过计划没？  如果没有那我这边抽时间来个 pr ~

**Comment by jcc** [comment]
@raisezhang 你好，暂时还没有计划，如果你有时间可提 PR 给我。谢谢

**Comment by jcc** [comment]
@raisezhang 回头看，默认设置值是支持地区编码的。
