### ISSUE TITLE
用cdn直接引入 不显示区的输入框

### ISSUE THREAD

**Issue by hfq-chenkeke** [jcc/v-distpicker#39]
用cdn直接引入 不显示区的输入框，怎么解决

**Comment by jcc** [comment]
全局样式覆盖即可

**Comment by hfq-chenkeke** [comment]
是不是我没有引用你的css的问题

**Comment by hfq-chenkeke** [comment]
引用那个css那？

**Comment by jcc** [comment]
你是怎么引用的？css 是附带在组件上的，不需要另外引入

**Comment by hfq-chenkeke** [comment]
<script type="text/javascript" src='../js/v-distpicker.js'></script>

**Comment by hfq-chenkeke** [comment]
我下载的你的master的dist下面的js源码，

**Comment by hfq-chenkeke** [comment]
结果发现只有省市，默认不显示区，只有选择了省市才能显示区,我现在想默认就显示区

**Comment by jcc** [comment]
因为香港澳门没有区，所以默认没有显示了。我想想这块怎么处理。

**Comment by hfq-chenkeke** [comment]
没有区，就默认展示呗，只是他不填写就好呀，

**Comment by hfq-chenkeke** [comment]
或者把香港澳门的区，默认填写成  香港特别行政区 澳门特别行政区

**Comment by jcc** [comment]
也可以，这样吧，我晚点设置回默认显示，然后区那块如果没有就禁止选择。这样应该可以

**Comment by jcc** [comment]
@hfq-chenkeke 如果你有空也可以提 pr 给我哦。我要晚点才能改，现在在忙其他。哈

**Comment by hfq-chenkeke** [comment]
恩恩，那我就先做别的，你弄好能告诉我吗，我先调试别的，以为我今天必须用完，自己还不会写这个级联，你大概什么时间，因为晚上要提测了，我等你弄完

**Comment by jcc** [comment]
你等的话，我尽量在晚上前搞好啦

**Comment by hfq-chenkeke** [comment]
我等，以为用过那么省市联动的，就你写这个最好用

**Comment by hfq-chenkeke** [comment]
因为

**Comment by jcc** [comment]
@hfq-chenkeke update 一下版本
