### ISSUE TITLE
如何reset呢

### ISSUE THREAD

**Issue by pangtengfei** [jcc/v-distpicker#4]
有没有重置的方法？ 非mobile

**Comment by jcc** [comment]
重置方法父组件控制即可。

**Comment by pangtengfei** [comment]
<distpicker class="distpicker-container"
                                        :province="unitBelongsProvince"
                                        :city="unitBelongsCity"
                                        :placeholders="placeholders"
                                        @province="selectProvince"
                                        @city="selectCity"
                                        hide-area></distpicker>

设置unitBelongsProvince=“” 不起作用

**Comment by jcc** [comment]
@pangtengfei 你是什么情景下重置？

**Comment by pangtengfei** [comment]
表单提交
![image](https://cloud.githubusercontent.com/assets/1397432/25417041/e3622ed2-2a73-11e7-9be5-21d9d69c8f5b.png)

![image](https://cloud.githubusercontent.com/assets/1397432/25417027/ccdea104-2a73-11e7-942c-6915ecf3bf8d.png)

**Comment by jcc** [comment]
@pangtengfei 好的。我看到问题了。

**Comment by pangtengfei** [comment]
建议更新下dist
