### ISSUE TITLE
当选择的是香港澳门等没有区的时候，数据无法获取

### ISSUE THREAD

**Issue by DongFangWuShuang** [jcc/v-distpicker#40]
我获取数据是通过@selected="onSelected"来赋值的，当选择澳门、香港的时候，只有前面两个选项，第三个（县）没有了，数据不改变，这个应该是属于selected的方法不完善。请问如何修复

**Comment by jcc** [comment]
@DongFangWuShuang 第三个省份没有了？什么意思

**Comment by zht0102** [comment]
the same problem

**Comment by jcc** [comment]
@DongFangWuShuang @zht0102 update 一下版本试一下

**Comment by DongFangWuShuang** [comment]
@jcc 澳门、香港等地，是只有两个选项，无县这个说法，因此我clone下来的代码，没有触发您内置的方法，也就是说，无法得到选择后的数据。

**Comment by jcc** [comment]
@DongFangWuShuang 你 Update 了最新版本没？

**Comment by Bkengs** [comment]
选择台湾时，触发不了selected事件

**Comment by jcc** [comment]
@Bkengs 更新版本再试一下
