### ISSUE TITLE
我怎样才能在vue里拿到选择的省市区信息的值？

### ISSUE THREAD

**Issue by yelexin** [jcc/v-distpicker#41]
怎样才能获取到选择的省市区的值？绑定v-model无效

**Comment by jcc** [comment]
[https://distpicker.iline.co/](https://distpicker.iline.co/) 看文档。现在暂不支持 `v-model`

**Comment by yelexin** [comment]
认为文档里Mehtods写成Events比较好吧，已经解决。@procvince="somefunc"，@city这种事件绑定到函数。拿到data。
