### ISSUE TITLE
在组件中使用以后更改不了样式啊 ??

### ISSUE THREAD

**Issue by feng9217** [jcc/v-distpicker#42]
![image](https://user-images.githubusercontent.com/6224010/35313423-4295a858-00fb-11e8-982d-293b5ce02b7a.png)
想做出和上面 input 框一样的效果 但是好像怎么也选不到 v-distpicker啊 ??
用了less 和 stylus
![image](https://user-images.githubusercontent.com/6224010/35313469-7866b90e-00fb-11e8-83b1-88a52320d3b9.png)
![image](https://user-images.githubusercontent.com/6224010/35313459-62f34420-00fb-11e8-9463-03b5d5fe3d40.png)
刚开始还以为是因为 stylus或者是 scoped限制了 后来换了发现还是不行 
求助啊 !!!

**Comment by jcc** [comment]
加上 `!important` 试试

**Comment by feng9217** [comment]
@jcc 
谢回 加上了 仍没变化
css
![image](https://user-images.githubusercontent.com/6224010/35314135-11307f6e-00ff-11e8-94ef-c7820d3d98ce.png)
完整的html
![image](https://user-images.githubusercontent.com/6224010/35314158-3ba8d6f6-00ff-11e8-8e2c-2aded3216a28.png)
浏览器里看 上级目录是根据样式修改了的 但是到了 v-distpicker 就完全选不到了 ..
![image](https://user-images.githubusercontent.com/6224010/35314300-2c42d9f4-0100-11e8-93d3-dcf61420739f.png)

**Comment by jcc** [comment]
你要改的是 select 框吧？你改 div 没用的吧。

**Comment by feng9217** [comment]
div大小 select大小一起改
在select加了 !important 但是并没有发生变化

现在听我同事的 在index 导入了个 base.css 在里面修改样式反而成了
![image](https://user-images.githubusercontent.com/6224010/35314870-f410ce34-0103-11e8-932a-24b9555ca8bc.png)
效果:
![image](https://user-images.githubusercontent.com/6224010/35314878-03735400-0104-11e8-80eb-c05057f30097.png)

amazing!!

**Comment by jcc** [comment]
emmm...这样的情况就是要全局才行。我迟点看看能不能优化一下这块吧

**Comment by feng9217** [comment]
好 !! 期待优化!!
