### ISSUE TITLE
V - Distpicker 是一个简单易用的地区选择器

### ISSUE THREAD

**Issue by ABCDEFboy** [jcc/v-distpicker#43]
![default](https://user-images.githubusercontent.com/26833337/35369115-75f906b0-01c1-11e8-819b-60c6986c153c.png)

 您好，想请教一下 V - Distpicker 的reset重置具体是怎样实现的呢？因为官方文档没有具体的代码，麻烦了，谢谢

**Comment by jcc** [comment]
可以看看这里的事例代码。[https://github.com/jcc/v-distpicker/blob/master/examples/components/BaseUsage/ResetButton.vue](https://github.com/jcc/v-distpicker/blob/master/examples/components/BaseUsage/ResetButton.vue)
