### ISSUE TITLE
base

### ISSUE THREAD

**Issue by hfq-chenkeke** [jcc/v-distpicker#44]
![image](https://user-images.githubusercontent.com/27851284/36625107-2322c228-1954-11e8-8a70-a3fb786bf67e.png)

这个值是什么拿到的

**Comment by jcc** [comment]
![image](https://user-images.githubusercontent.com/12684082/36651621-c184c9fc-1ae4-11e8-9f98-cabf2ee60d51.png)
哈，文档有些，methods
