### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by jl1014171068** [jcc/v-distpicker#46]
v-distpicker version
^1.0.16

vue version 
v2.5.15

"nuxt": "^1.0.0"

What is actually happening?
引入组件即报错
![image](https://user-images.githubusercontent.com/12130044/37264506-9ed9d01e-25e8-11e8-84ce-5ff461e9a7fb.png)

**Comment by jcc** [comment]
请你贴出报错信息!

**Comment by jl1014171068** [comment]
![image](https://user-images.githubusercontent.com/12130044/37264675-c5a88a86-25e9-11e8-805f-c25f40bc30dd.png)
@jcc 应该是使用nuxt的原因了

**Comment by jcc** [comment]
@jl1014171068 看不错跟这个包有什么关系。你看看 nuxt 包引入，看报错信息是 nuxt 的配置问题

**Comment by jl1014171068** [comment]
// .vue 页面
if (process.browser) {
  var Distpicker = require('v-distpicker')
  Vue.use(Distpicker)
  Vue.component('v-distpicker', Distpicker)
}

// nuxt.config.js
build: {
    vendor: ['v-distpicker']
}

**Comment by jl1014171068** [comment]
补充：这样修改后会报错：[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.

在需要使用的地方修改为：
<no-ssr><v-distpicker :placeholders="form.placeholders"></v-distpicker></no-ssr>
