### ISSUE TITLE
文档地址打不开了。

### ISSUE THREAD

**Issue by cq-guojia** [jcc/v-distpicker#47]
http://distpicker.iline.co/
文档地址打不开了。急。。

**Comment by jcc** [comment]
https://distpicker.uine.org 用这个

**Comment by Eamonnzhang** [comment]
为什么不更新一下readme呢？@jcc

**Comment by jcc** [comment]
@Eamonnzhang 稍等，忘了。

**Comment by jcc** [comment]
@Eamonnzhang https://distpicker.pigjian.com/
