### ISSUE TITLE
请问下能否支持多个国家

### ISSUE THREAD

**Issue by vxhly** [jcc/v-distpicker#49]
因为项目需求，可能要做别的国家的地区选择，大佬这组件非常符合项目需求，所以有接口或者什么参数可以传入别的国家地区 json 文件，然后就能应用了？

**Comment by jcc** [comment]
这个暂时不支持其他国家的。因为其他国家一般不会分 3 层。这个以后会考虑。

**Comment by vxhly** [comment]
州 省 区 ，够了啊，刚刚稍微看一下源码，我只要知道其他国家地区的邮编就行了 
![image](https://user-images.githubusercontent.com/17906558/38019136-5f2f1a6e-32a9-11e8-84cd-091ac4c424df.png)
ra 然后重写一下 districts.js 就行了，但是很尴尬，我并不知道。。。

**Comment by jcc** [comment]
哈哈，这些编码需要收集，你需要哪些国家的？

**Comment by vxhly** [comment]
没关系，我已经找到网站可以查询了 https://www.youbianku.com/%E5%9B%BD%E9%99%85 ，手上的项目也是蛮奇葩的，公司客户发展到那个国家，就要有那个国家的地区选择，所以大佬还是要多支持几个国家

**Comment by jcc** [comment]
好哒，最近我有点忙，我忙完看看。暂时没那么快支持哦。如果可以的话，提交一个 pr 给我
