### ISSUE TITLE
selected方法小bug？

### ISSUE THREAD

**Issue by ZYSzys** [jcc/v-distpicker#52]
从选择好的省市区再重新改为默认的placeholder值时，onselect方法貌似没有触发，这样之前传递进去的值也没有改变，貌似有点难以判断用户是否选择完整省市区了。
我想监听到选回到默认placeholder到行为，应该要怎么优化呢？🤕

**Comment by jcc** [comment]
@ZYSzys 你是指选了省市区后改为默认的 `placeholder` 需要出发 `selected` 事件？

**Comment by jcc** [comment]
这里你选 placeholder 的值的话，完全没有会用到 selected 的情况吧。也就是说你选了，你还要清空原来的值？

**Comment by ZYSzys** [comment]
emmm,差不多是的，我想选回placeholder时，对应绑定的值也能监听到并作出相应的更改，

**Comment by jcc** [comment]
因为我觉得没必要的。或者你试试 `@privince`、`@city`、`@area`

**Comment by ZYSzys** [comment]
文档的placeholder能监听到变化，所以文档也是用的 @privince、@city、@area方法吗？
![screen shot 2018-05-26 at 4 51 25 pm](https://user-images.githubusercontent.com/23313266/40574485-43da6086-6105-11e8-8963-d7efbf6ca739.png)

**Comment by ZYSzys** [comment]
好的，楼主很有耐心，谢谢啦
