### ISSUE TITLE
可以加下台湾省的城市选择吗

### ISSUE THREAD

**Issue by xu455255849** [jcc/v-distpicker#55]
现在点进去，一个空的选项让人觉得是bug ，没法用啊

**Comment by jcc** [comment]
@xu455255849 台湾区号只有一个。我看怎么把市加入吧

**Comment by xu455255849** [comment]
@jcc   如果不方便，可以在源码先把台湾去掉，这样用起来 也不会感觉像bug ，麻烦了。

**Comment by xu455255849** [comment]
老哥， 台湾省的问题还没解决吗？  没区号 没大问题，主要是省市区的选择

**Comment by jcc** [comment]
@xu455255849 今天对比了维基数据，修改了很多的地区，也加入了台湾地区。

**Comment by xu455255849** [comment]
> @xu455255849 今天对比了维基数据，修改了很多的地区，也加入了台湾地区。感谢你的支持

还是得感谢你们开源这些插件库，我已经fork了一个版本 修改过地区数据满足开发了
