### ISSUE TITLE
地区数据可以自定义吗

### ISSUE THREAD

**Issue by testllj** [jcc/v-distpicker#58]
地区数据可以自定义吗

**Comment by sunnymask** [comment]
> 地区数据可以自定义吗

我也想问这个问题

**Comment by jcc** [comment]
@sunnymask 暂时不支持的。

**Comment by sunnymask** [comment]
> @sunnymask 暂时不支持的。

嗯，谢谢，解决了，我用了你的源码改了下

**Comment by jaling530** [comment]
Default Value选择区域后，没有重置按钮代码。是不是赋值成这样，select: { province: '', city: '', area: '' },？？

**Comment by jcc** [comment]
@jaling530 是的

**Comment by jaling530** [comment]
好的，谢谢。街道什么时候可以出呢。v-region组件有街道，但是它文档没有说怎么清空
