### ISSUE TITLE
如何重置数据

### ISSUE THREAD

**Issue by jinlihong** [jcc/v-distpicker#59]
官方实例的reset示范例子, 请问如何实现的?

**Comment by jcc** [comment]
https://github.com/jcc/v-distpicker/blob/master/examples/components/BaseUsage/ResetButton.vue

**Comment by lyb66666** [comment]
试过了，不可实现，麻烦还请您试一试再说

**Comment by ashur816** [comment]
data中必须要加入相应的赋值，不然不起作用，如
` data() {
            return {
queryParams: {
                    province: "",
                    city: "",
                    district: "",
}
}
}`
