### ISSUE TITLE
请问districts.js 中的全国城市数据是哪里来的啊 ？

### ISSUE THREAD

**Issue by zhangmin2020** [jcc/v-distpicker#6]
想知道 全国城市数据 的来源是哪里的奥   然后是怎么处理成 districts.js 中的形式的  
谢谢

**Comment by jcc** [comment]
数据可以从全国省市区数据库获取，此 package 的数据主要参考 [https://github.com/fengyuanchen/distpicker](https://github.com/fengyuanchen/distpicker) 此项目的。

你可以根据全国省市区数据库的 ID 和 ID 的关系排列成你所需的数据结构。
[https://github.com/eduosi/district](https://github.com/eduosi/district)

**Comment by zhangmin2020** [comment]
多谢啦
