### ISSUE TITLE
nuxt框架下，f5刷新网页会报错

### ISSUE THREAD

**Issue by lllllleo-chan** [jcc/v-distpicker#60]
nuxt框架下，局部引入后跳转进入正常，f5刷新网页会报错：render function or template not defined in component: anonymous

**Comment by jcc** [comment]
看看这个 [https://github.com/NightCatSama/vue-slider-component/issues/114#issuecomment-353827607](https://github.com/NightCatSama/vue-slider-component/issues/114#issuecomment-353827607)

**Comment by jcc** [comment]
https://github.com/nuxt/nuxt.js/issues/1041

**Comment by lllllleo-chan** [comment]
谢谢，刚刚解决了`// plugins/distpicker.js
import Vue from 'vue'
import VDistpicker from 'v-distpicker'

export default () => {
	Vue.use(VDistpicker)
	Vue.component('v-distpicker', VDistpicker)
}
// nuxt.config.js
plugins: [
		{src: '@/plugins/distpicker', ssr: false},
	],`
