### ISSUE TITLE
市区始终没有添加选中状态

### ISSUE THREAD

**Issue by qbob** [jcc/v-distpicker#63]
![image](https://user-images.githubusercontent.com/1908445/46130532-23579900-c26c-11e8-8999-71107fc56e4c.png)

返回市区始终没有添加选中状态

经过测试，注释两行代码：
 getCities () {
            // this.currentCity = this.placeholders.city
            // this.currentArea = this.placeholders.area
            this.cities = this.determineValue(this.currentProvince, this.placeholders.province)
            this.cleanList('areas')
            if (this.cities.length === 0) {
                this.emit('selected')
                this.tab = 1
                this.showCityTab = false
            }
        },

**Comment by jcc** [comment]
@qbob 没发现有问题！？
