### ISSUE TITLE
报错（error）

### ISSUE THREAD

**Issue by lingangle** [jcc/v-distpicker#66]
Uncaught Error: Module build failed: Error: Missing binding /Users/jian/Sites/distpicker/node_modules/node-sass/vendor/darwin-x64-64/binding.node
Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 10.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 9.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.

出现如上报错信息，请问可以怎么解决？（How to solve these problems）

**Comment by jcc** [comment]
删掉 node_modules 重新安装一下。

**Comment by lingangle** [comment]
删除过了，也还是出现这个问题。谢谢*_*

**Comment by jcc** [comment]
`npm rebuild node-sass --force`

**Comment by lingangle** [comment]
我尝试过这种解决方案，还是相同的错误

**Comment by jcc** [comment]
看上去是因为你升级了 node 把呢本导致的。全局的 node_modules 更新一下。

**Comment by lingangle** [comment]
Node版本应该不会自己升级吧，全局更新我使用的是npm updata -g，然后重新npm install,然后npm run dev，报相同的错。谢谢。

**Comment by jcc** [comment]
@lingangle Update 最新的试一下。1.0.20

**Comment by lingangle** [comment]
thankyou~~~~
