### ISSUE TITLE
请问一下，select的样式好像覆盖不了

### ISSUE THREAD

**Issue by grandetime** [jcc/v-distpicker#67]
使用插件：
![image](https://user-images.githubusercontent.com/44169029/48117974-c78a2200-e2a5-11e8-8c7a-f411f6965d41.png)
覆盖样式：
![image](https://user-images.githubusercontent.com/44169029/48118038-faccb100-e2a5-11e8-9bad-2f29faf385d5.png)
但是在浏览器端：样式没有覆盖掉
![image](https://user-images.githubusercontent.com/44169029/48118155-66168300-e2a6-11e8-9401-07fbd6db218f.png)

**Comment by jcc** [comment]
加 `!important` 强制覆盖一下
