### ISSUE TITLE
点击事件在ios上错位的问题

### ISSUE THREAD

**Issue by sunnymask** [jcc/v-distpicker#68]
在安卓机上是好的，但是在ios中，绑定的点击事件会错位，点击得到的和实际点击的不是同一个值

**Comment by jcc** [comment]
@sunnymask 点击时间错误是指？

**Comment by sunnymask** [comment]
https://github.com/sunnymask/wechat-app/blob/master/img-folder/7fd01f0c09e06a8dd1a4cb0a826123b5.mp4?raw=true
安卓没有问题
ios：首先我选了浙江省，没问题，然后我又点了第一个杭州市，结果选中的是温州市（这里如果选择省的时候往下滑动过，选市的时候就会出现这个bug（这里选市如果再随便滑动一下列表，选的时候也不会有问题）；如果选择省没有滑动则选市没有问题），然后我再返回选择杭州市就没有问题了。
我觉得可能是切换的时候，vue绑定事件错位导致的
