### ISSUE TITLE
mobile模式下如何reset,selected方法若点击上一次的区，无法触发

### ISSUE THREAD

**Issue by ChaosHf** [jcc/v-distpicker#70]
第一次选择完省市区后，重新点击上一次选择的区，无法触发selected方法。

**Comment by jcc** [comment]
@ChaosHf `selected` 只有选择区的时候才会触发

**Comment by jcc** [comment]
@ChaosHf 这个应该是没问题的吧。你看看 Trigger Event 的例子。
