### ISSUE TITLE
地区GB2260编码重复bug

### ISSUE THREAD

**Issue by JayChen1195** [jcc/v-distpicker#71]
![0c60ec2c7b7f5ddf93de09689568d8a8](https://user-images.githubusercontent.com/29937603/48901200-a02f7980-ee8f-11e8-929d-ac76df5de939.jpg)

### 选择的地址与GB2260编码不匹配。选择的是广东省深圳市南山区，但返回的code却是黑龙江省鹤岗市南山区的code。

**Comment by JayChen1195** [comment]
![a9bf0dd1-ba2f-46d2-bbdd-f8756bbd1c77](https://user-images.githubusercontent.com/29937603/48926224-fbe91980-ef06-11e8-912e-54ce9caa62c6.png)
### 官网Demo也存在这样的问题

**Comment by jcc** [comment]
@JayChen1195 更新一下版本 `v1.0.21`
