### ISSUE TITLE
选择区的时候的bug

### ISSUE THREAD

**Issue by chenjiejing** [jcc/v-distpicker#76]
需求有个模糊搜索的功能,选择了其中一个区,再选择回'区'这样想,area会默认回是上一个area的值,不会主动清空,也触发不了onSelected事件,请问要怎么解决?

**Comment by randolph2014** [comment]
我也碰到过这个问题....区的信息选择以后，然后再选回'区'的时候，是不会触发到onSelected时间....最新1.1.0，有这个问题

**Comment by jcc** [comment]
选择区也会触发事件了
