### ISSUE TITLE
初始值设置能否使用使用code来指定

### ISSUE THREAD

**Issue by flight9** [jcc/v-distpicker#78]
### 需求: 
1. 由于我们数据表实际保存的是最后一个字段 area 的 code, 比如: 110118(密云区), 而不是分别存'省/市/区',
(因为 110118 就能唯一确定 '省/市/区' 三级了)
那么在下次装载时, 能否在控件初始化时就使用 `<v-distpicker area-code="110118"></v-distpicker>` 就把'北京市 - 北京城区 - 密云区'自动选择好？
目前的必须用具体'省/市/区'名字指定初始值, 没法满足上面需求。
2. 能否开放一个方法 getDistObject(areaCode) 从代码获取具体三级  '省/市/区'？
输入: areaCode (地区编码)
输出: {province, city, area} 的具体名称和code

组件写的很好, 感谢！

小提醒: 说明文档 https://distpicker.pigjian.com/ 尾部 Methods 方法 列出现两个 city(有一个应该 area)

**Comment by chenny** [comment]
强烈建议加一个.

**Comment by fulus06** [comment]
已经可以code设置
`<v-distpicker @selected="selectProjectAreaCodeHandler" :province="150000" :city="150600" :area="150621" ></v-distpicker>     `

**Comment by 15939054361** [comment]
## 如果是后来赋值 好像就会出错 直接什么都不显示了
```
 <v-distpicker @selected="codeSelected" :province="province" :city="city" :area="area" />
```
![image](https://user-images.githubusercontent.com/52627267/74395280-dfa60500-4e49-11ea-9029-9e488b8fcc5b.png)
![image](https://user-images.githubusercontent.com/52627267/74395297-eb91c700-4e49-11ea-93ef-d8f610e8fcd7.png)
![image](https://user-images.githubusercontent.com/52627267/74395333-049a7800-4e4a-11ea-9534-30c5df7bfd59.png)

**Comment by simpsonyang** [comment]
我也遇到同样的问题，初始赋值用code没问题，但是后面再改变code没有效果。
var vm = new Vue({
        el: "#app",
        data:{
            //这样设置可以工作
            select: { province: 440000, city:440100', area:440103 }
        },
        methods:{
            changeProvince() {
               //从后台获取数据，然后赋值，会像上面帖子一样变成空白。
                this.select.province = 110000;
            },

**Comment by leemem** [comment]
我也遇到同样的问题，对代码做了一下修改就可以了
在 watch中，参考created 里面的做法
`
province(value) {
      //this.currentProvince = this.province || this.placeholders.province  //原来的代码
      this.currentProvince = this.determineType(this.province) || this.placeholders.province //修改后的代码
      this.cities = this.determineValue('province', this.currentProvince, this.placeholders.province)
    },
    city(value) {
      // this.currentCity = this.city || this.placeholders.city //原来的代码
      this.currentCity = this.determineType(this.city) || this.placeholders.city //修改后的代码
      this.areas = this.determineValue('city', this.currentCity, this.placeholders.city, this.currentProvince)
    },
    area(value) {
      //this.currentArea = this.area || this.placeholders.area //原来的代码
      this.currentArea = this.determineType(this.area) || this.placeholders.area  //修改后的代码
    }
`
另外，如果是通过code设置值，需要确定值为数字，不能是字符串

**Comment by wwhwwhwwh** [comment]
@flight9  v1.3.1 已实现
