### ISSUE TITLE
select css无法修改。！important也没作用

### ISSUE THREAD

**Issue by arlen-s** [jcc/v-distpicker#79]
distpicker-address-wrapper 这个class有效。但是distpicker-address-wrapper select{}就没有作用

**Comment by arlen-s** [comment]
而且还有个问题，demo在电脑上选择地址后。是空白的。手机端正常

**Comment by arlen-s** [comment]
![qq 20190226115155](https://user-images.githubusercontent.com/27278140/53386392-06f78e00-39bd-11e9-8806-59bdae4db32a.png)
![_20190226115118](https://user-images.githubusercontent.com/27278140/53386394-06f78e00-39bd-11e9-8bdf-77bb559a24fc.png)

**Comment by mrlizonglin** [comment]
这个问题有修复了吗？我现在也遇到了.......

**Comment by jcc** [comment]
全局修改或者使用 `wrapper` 属性替换 class
