### ISSUE TITLE
country/region/city

### ISSUE THREAD

**Issue by huglester** [jcc/v-distpicker#8]
Hello,

is there any alternative, to support country/region (not always)/city?

Thanks

**Comment by jcc** [comment]
You want to replace the `districts.js` file？Can you show me your scene?

**Comment by huglester** [comment]
I will probably just take this library as a source... and rewrite it a bit.
What I need is: 
1. user selects Country
2. if country has regions - it shows region list, if not show cities;
3. show cities (if country had regions), if not - skip .

something along these lines!

**Comment by jcc** [comment]
@huglester I think you should sort out the data for countries - regions - cities. And than set hide-area to control your need.

**Comment by huglester** [comment]
yeah that's what I think of! :)

I like the mobile example, it's very similar to what I wanted
