### ISSUE TITLE
能否将地区名修改为与小程序端一致

### ISSUE THREAD

**Issue by elfman** [jcc/v-distpicker#80]
有些地区名称与小程序的地区选择组件不对应，在后台设置好了却在小程序端找不到，增加了搜索匹配的难度，比如“北京城区”在小程序端是“北京市”，“天津城区”在小程序端是“天津市”。
能否修改为与小程序端一致，这样使用起来更容易一些，小程序端自制组件太麻烦了

**Comment by jcc** [comment]
@elfman 这个我迟点收集一下，因为不同平台的库，都有点区别的。
