### ISSUE TITLE
可以根据code获取value吗

### ISSUE THREAD

**Issue by jiagushuai** [jcc/v-distpicker#82]
数据库保存code,然后有方法可以输入code返回得到value吗

**Comment by jcc** [comment]
有，默认值你输入 `code` 就可以了。

**Comment by jiagushuai** [comment]
直接输入code吗，但是显示不对，怪怪的
![image](https://user-images.githubusercontent.com/29997741/55525679-9aab3100-56c4-11e9-8bb2-12059afc8dd2.png)

**Comment by jiagushuai** [comment]
thanks
