### ISSUE TITLE
请问如何修改样式呢

### ISSUE THREAD

**Issue by KKZOOMz** [jcc/v-distpicker#93]
请问如何修改样式，默认的字体有点大，请问如何改小，另外如何控制选择框的宽度恒定，内容超出则隐藏呢

**Comment by ButcherV** [comment]
![image](https://user-images.githubusercontent.com/12529975/63684813-63365000-c830-11e9-92a2-d1581387e70e.png)

**Comment by ButcherV** [comment]
https://distpicker.pigjian.com/ attributes 表格的最下方有介绍。
